#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$ROOT_DIR/dist/installers"
CACHE_DIR="$ROOT_DIR/.packaging-cache"
APP_NAME="fangxingwei-ai"
JAR_SOURCE="$ROOT_DIR/backend/target/repair-0.0.1-SNAPSHOT.jar"

PLATFORM_ARG="all"
SKIP_BUILD=0
SYNC_MYSQL_DATA=0
MYSQL_HOST="${MYSQL_HOST:-localhost}"
MYSQL_PORT="${MYSQL_PORT:-3306}"
MYSQL_DATABASE="${MYSQL_DATABASE:-car_repair}"
MYSQL_USERNAME="${MYSQL_USERNAME:-root}"
MYSQL_PASSWORD="${MYSQL_PASSWORD:-79Haolubenwei}"
MYSQL_SNAPSHOT="$CACHE_DIR/mysql-snapshot/standalone-mysql-data.sql"

usage() {
  cat <<'USAGE'
Usage: scripts/package-release.sh [--platform all|windows-x64|macos-x64|macos-arm64|current] [--skip-build] [--sync-mysql-data]

Builds portable one-click packages with an embedded JRE and local H2 data store.
End users do not need Java, Node.js, Maven, or MySQL installed.

Windows archives are created with the JDK jar tool so Chinese launcher names are
stored with the ZIP UTF-8 language encoding flag. Do not re-pack Windows bundles
with plain zip -qr, which can produce garbled filenames on Windows.

Use --sync-mysql-data to export the current MySQL car_repair data into the
package. The snapshot is imported into the package-local H2 database on first
startup, so end users still do not need MySQL.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --platform)
      PLATFORM_ARG="${2:-}"
      shift 2
      ;;
    --skip-build)
      SKIP_BUILD=1
      shift
      ;;
    --sync-mysql-data)
      SYNC_MYSQL_DATA=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

detect_current_platform() {
  local os arch
  os="$(uname -s)"
  arch="$(uname -m)"
  case "$os:$arch" in
    Darwin:arm64) echo "macos-arm64" ;;
    Darwin:x86_64) echo "macos-x64" ;;
    MINGW*:x86_64|MSYS*:x86_64|CYGWIN*:x86_64) echo "windows-x64" ;;
    *) echo "Unsupported current platform: $os $arch" >&2; exit 1 ;;
  esac
}

resolve_platforms() {
  case "$PLATFORM_ARG" in
    all) echo "windows-x64 macos-x64 macos-arm64" ;;
    current) detect_current_platform ;;
    windows-x64|macos-x64|macos-arm64) echo "$PLATFORM_ARG" ;;
    *) echo "Unsupported platform: $PLATFORM_ARG" >&2; exit 1 ;;
  esac
}

build_application() {
  echo "==> Building frontend"
  (cd "$ROOT_DIR/frontend" && npm ci && npm run build)

  echo "==> Building backend jar"
  (cd "$ROOT_DIR/backend" && ./mvnw -DskipTests package)
}

mysql_tables_for_snapshot() {
  local mysql_args=(
    "--host=$MYSQL_HOST"
    "--port=$MYSQL_PORT"
    "--user=$MYSQL_USERNAME"
    "--password=$MYSQL_PASSWORD"
  )
  mysql "${mysql_args[@]}" -N -B "$MYSQL_DATABASE" -e "
    SELECT TABLE_NAME
    FROM information_schema.TABLES
    WHERE TABLE_SCHEMA = '$MYSQL_DATABASE'
      AND TABLE_TYPE = 'BASE TABLE'
      AND TABLE_NAME NOT IN ('flyway_schema_history', 'auth_refresh_token')
    ORDER BY TABLE_NAME;
  "
}

generate_mysql_snapshot() {
  if [[ "$SYNC_MYSQL_DATA" -eq 0 ]]; then
    rm -f "$MYSQL_SNAPSHOT"
    return
  fi

  if ! command -v mysql >/dev/null 2>&1 || ! command -v mysqldump >/dev/null 2>&1; then
    echo "mysql and mysqldump are required when --sync-mysql-data is used" >&2
    exit 1
  fi

  echo "==> Exporting MySQL data snapshot from $MYSQL_HOST:$MYSQL_PORT/$MYSQL_DATABASE"
  mkdir -p "$(dirname "$MYSQL_SNAPSHOT")"

  local tables=()
  while IFS= read -r table; do
    tables+=("$table")
  done < <(mysql_tables_for_snapshot)
  if [[ "${#tables[@]}" -eq 0 ]]; then
    echo "No tables found in MySQL database: $MYSQL_DATABASE" >&2
    exit 1
  fi

  local mysql_args=(
    "--host=$MYSQL_HOST"
    "--port=$MYSQL_PORT"
    "--user=$MYSQL_USERNAME"
    "--password=$MYSQL_PASSWORD"
  )

  {
    printf '%s\n' "-- Generated by scripts/package-release.sh --sync-mysql-data"
    printf '%s\n' "SET REFERENTIAL_INTEGRITY FALSE;"
    mysqldump "${mysql_args[@]}" \
      --single-transaction \
      --set-gtid-purged=OFF \
      --no-tablespaces \
      --no-create-info \
      --complete-insert \
      --skip-triggers \
      --skip-add-locks \
      --skip-disable-keys \
      --skip-comments \
      --compact \
      --default-character-set=utf8mb4 \
      "$MYSQL_DATABASE" "${tables[@]}" \
      | sed 's/\\"/"/g'
    printf '%s\n' "SET REFERENTIAL_INTEGRITY TRUE;"
  } > "$MYSQL_SNAPSHOT"
}

adoptium_url() {
  local platform="$1"
  case "$platform" in
    windows-x64) echo "https://api.adoptium.net/v3/binary/latest/17/ga/windows/x64/jre/hotspot/normal/eclipse?project=jdk" ;;
    macos-x64) echo "https://api.adoptium.net/v3/binary/latest/17/ga/mac/x64/jre/hotspot/normal/eclipse?project=jdk" ;;
    macos-arm64) echo "https://api.adoptium.net/v3/binary/latest/17/ga/mac/aarch64/jre/hotspot/normal/eclipse?project=jdk" ;;
    *) echo "Unsupported platform: $platform" >&2; exit 1 ;;
  esac
}

java_binary_name() {
  local platform="$1"
  if [[ "$platform" == windows-* ]]; then
    echo "java.exe"
  else
    echo "java"
  fi
}

archive_name() {
  local platform="$1"
  if [[ "$platform" == windows-* ]]; then
    echo "$platform-jre.zip"
  else
    echo "$platform-jre.tar.gz"
  fi
}

download_runtime() {
  local platform="$1"
  local runtime_dir="$CACHE_DIR/jre/$platform"
  local java_name
  java_name="$(java_binary_name "$platform")"

  if [[ -x "$runtime_dir/bin/$java_name" ]]; then
    echo "==> Reusing cached JRE for $platform"
    return
  fi

  rm -rf "$runtime_dir"
  mkdir -p "$runtime_dir" "$CACHE_DIR/downloads" "$CACHE_DIR/extract/$platform"

  local archive="$CACHE_DIR/downloads/$(archive_name "$platform")"
  local url
  url="$(adoptium_url "$platform")"

  echo "==> Downloading Temurin JRE 17 for $platform"
  curl -L --fail --retry 3 -o "$archive" "$url"

  rm -rf "$CACHE_DIR/extract/$platform"
  mkdir -p "$CACHE_DIR/extract/$platform"

  if [[ "$archive" == *.zip ]]; then
    unzip -q "$archive" -d "$CACHE_DIR/extract/$platform"
  else
    tar -xzf "$archive" -C "$CACHE_DIR/extract/$platform"
  fi

  local java_path runtime_root
  java_path="$(find "$CACHE_DIR/extract/$platform" -type f -path "*/bin/$java_name" | head -n 1)"
  if [[ -z "$java_path" ]]; then
    echo "Could not locate $java_name in extracted runtime for $platform" >&2
    exit 1
  fi

  runtime_root="$(cd "$(dirname "$java_path")/.." && pwd)"
  cp -R "$runtime_root"/. "$runtime_dir"/
}

write_windows_launchers() {
  local bundle="$1"
  mkdir -p "$bundle/scripts"

  cat > "$bundle/启动系统.bat" <<'EOF'
@echo off
set ROOT=%~dp0
powershell -NoProfile -ExecutionPolicy Bypass -File "%ROOT%scripts\start-windows.ps1"
pause
EOF

  cat > "$bundle/停止系统.bat" <<'EOF'
@echo off
set ROOT=%~dp0
powershell -NoProfile -ExecutionPolicy Bypass -File "%ROOT%scripts\stop-windows.ps1"
pause
EOF

  cat > "$bundle/scripts/start-windows.ps1" <<'EOF'
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$Java = Join-Path $Root "runtime\bin\java.exe"
$Jar = Join-Path $Root "app\backend.jar"
$DataDir = Join-Path $Root "data"
$LogDir = Join-Path $Root "logs"
$PidFile = Join-Path $DataDir "app.pid"
$Url = "http://localhost:8080"

New-Item -ItemType Directory -Force -Path $DataDir, $LogDir | Out-Null

if (Test-Path $PidFile) {
  $ExistingPid = Get-Content $PidFile -ErrorAction SilentlyContinue
  if ($ExistingPid -and (Get-Process -Id $ExistingPid -ErrorAction SilentlyContinue)) {
    Start-Process $Url
    Write-Host "The system is already running: $Url"
    exit 0
  }
}

$StdOut = Join-Path $LogDir "backend.log"
$StdErr = Join-Path $LogDir "backend.err.log"
$AppDataArg = "-DAPP_DATA_DIR=$DataDir"
$SnapshotArg = "-Dstandalone.mysql-snapshot.path=$(Join-Path $Root "app\mysql-snapshot.sql")"
$Args = @($AppDataArg, $SnapshotArg, "-jar", $Jar, "--spring.profiles.active=standalone")

$Process = Start-Process -FilePath $Java -ArgumentList $Args -WorkingDirectory $Root -RedirectStandardOutput $StdOut -RedirectStandardError $StdErr -WindowStyle Hidden -PassThru
Set-Content -Path $PidFile -Value $Process.Id

Write-Host "Starting the system, please wait..."
Start-Sleep -Seconds 8
Start-Process $Url
Write-Host "Started: $Url"
Write-Host "Default accounts: admin/user/tech/body, password: 123456"
EOF

  cat > "$bundle/scripts/stop-windows.ps1" <<'EOF'
$Root = Split-Path -Parent $PSScriptRoot
$PidFile = Join-Path $Root "data\app.pid"

if (!(Test-Path $PidFile)) {
  Write-Host "No running system was found."
  exit 0
}

$PidValue = Get-Content $PidFile -ErrorAction SilentlyContinue
if ($PidValue -and (Get-Process -Id $PidValue -ErrorAction SilentlyContinue)) {
  Stop-Process -Id $PidValue -Force
  Write-Host "The system has been stopped."
} else {
  Write-Host "The system process is no longer running."
}

Remove-Item $PidFile -Force -ErrorAction SilentlyContinue
EOF
}

write_macos_launchers() {
  local bundle="$1"

  cat > "$bundle/启动系统.command" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
JAVA="$ROOT/runtime/bin/java"
JAR="$ROOT/app/backend.jar"
DATA_DIR="$ROOT/data"
LOG_DIR="$ROOT/logs"
PID_FILE="$DATA_DIR/app.pid"
URL="http://localhost:8080"

mkdir -p "$DATA_DIR" "$LOG_DIR"

if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
  open "$URL"
  echo "系统已经在运行：$URL"
  exit 0
fi

nohup "$JAVA" \
  "-DAPP_DATA_DIR=$DATA_DIR" \
  "-Dstandalone.mysql-snapshot.path=$ROOT/app/mysql-snapshot.sql" \
  -jar "$JAR" \
  --spring.profiles.active=standalone \
  > "$LOG_DIR/backend.log" 2>&1 &

echo $! > "$PID_FILE"
echo "正在启动系统，请稍候..."
sleep 8
open "$URL"
echo "已启动：$URL"
echo "默认账号：admin/user/tech/body，密码均为 123456"
EOF

  cat > "$bundle/停止系统.command" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
PID_FILE="$ROOT/data/app.pid"

if [[ ! -f "$PID_FILE" ]]; then
  echo "没有找到正在运行的系统。"
  exit 0
fi

PID="$(cat "$PID_FILE")"
if kill -0 "$PID" 2>/dev/null; then
  kill "$PID"
  echo "系统已停止。"
else
  echo "系统进程已经不存在。"
fi

rm -f "$PID_FILE"
EOF

  chmod +x "$bundle/启动系统.command" "$bundle/停止系统.command"
}

write_bundle_readme() {
  local bundle="$1"
  cat > "$bundle/使用说明.txt" <<'EOF'
方行唯 AI 智能汽车维修系统 - 一键运行包

1. Windows：双击“启动系统.bat”。
2. macOS：双击“启动系统.command”；如果系统提示无法打开，请右键文件并选择“打开”。
3. 浏览器会自动打开 http://localhost:8080。
4. 默认演示账号：
   - 管理员：admin / 123456
   - 车主：user / 123456
   - 技师：tech / 123456
   - 钣喷技师：body / 123456
5. 本地数据保存在 data 目录。删除 data 会重置本机数据。
6. 需要关闭系统时，双击“停止系统”脚本。

本运行包内置 Java 运行时并使用本地文件数据库，不需要安装 Java、Node.js、Maven 或 MySQL。
EOF
}

to_crlf() {
  local file="$1"
  local tmp="$file.tmp"
  awk '{ sub(/\r$/, ""); printf "%s\r\n", $0 }' "$file" > "$tmp"
  mv "$tmp" "$file"
}

prepare_windows_text_files() {
  local bundle="$1"
  to_crlf "$bundle/启动系统.bat"
  to_crlf "$bundle/停止系统.bat"
  to_crlf "$bundle/使用说明.txt"
}

clean_runtime_state() {
  local bundle="$1"
  find "$bundle/data" "$bundle/logs" -mindepth 1 -exec rm -rf {} +
}

create_archive() {
  local platform="$1"
  local archive="$DIST_DIR/$APP_NAME-$platform.zip"

  rm -f "$archive"
  if [[ "$platform" == windows-* ]]; then
    # JDK jar writes UTF-8 ZIP filenames and sets the language encoding flag,
    # which prevents Chinese launcher filenames from becoming mojibake on Windows.
    jar --create --file "$archive" --no-manifest -C "$DIST_DIR" "$APP_NAME-$platform"
  else
    (cd "$DIST_DIR" && zip -qr "$APP_NAME-$platform.zip" "$APP_NAME-$platform")
  fi
}

create_bundle() {
  local platform="$1"
  local bundle="$DIST_DIR/$APP_NAME-$platform"
  local runtime_cache="$CACHE_DIR/jre/$platform"

  echo "==> Creating bundle: $platform"
  rm -rf "$bundle"
  mkdir -p "$bundle/app" "$bundle/runtime" "$bundle/data" "$bundle/logs"

  cp "$JAR_SOURCE" "$bundle/app/backend.jar"
  cp -R "$runtime_cache"/. "$bundle/runtime"/
  if [[ -f "$MYSQL_SNAPSHOT" ]]; then
    cp "$MYSQL_SNAPSHOT" "$bundle/app/mysql-snapshot.sql"
  fi

  if [[ "$platform" == windows-* ]]; then
    write_windows_launchers "$bundle"
  else
    write_macos_launchers "$bundle"
  fi

  write_bundle_readme "$bundle"
  if [[ "$platform" == windows-* ]]; then
    prepare_windows_text_files "$bundle"
  fi

  clean_runtime_state "$bundle"
  create_archive "$platform"
}

main() {
  if [[ "$SKIP_BUILD" -eq 0 ]]; then
    build_application
  fi

  generate_mysql_snapshot

  if [[ ! -f "$JAR_SOURCE" ]]; then
    echo "Backend jar not found: $JAR_SOURCE" >&2
    exit 1
  fi

  mkdir -p "$DIST_DIR"

  local platforms
  platforms="$(resolve_platforms)"
  for platform in $platforms; do
    download_runtime "$platform"
    create_bundle "$platform"
  done

  echo "==> Done. Packages are under $DIST_DIR"
}

main
